# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kocal/Dev/Client-Serveur/IUT-ClientServeur-MiniProjet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kocal/Dev/Client-Serveur/IUT-ClientServeur-MiniProjet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kocal/Dev/Client-Serveur/IUT-ClientServeur-MiniProjet/CMakeFiles /home/kocal/Dev/Client-Serveur/IUT-ClientServeur-MiniProjet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kocal/Dev/Client-Serveur/IUT-ClientServeur-MiniProjet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client.bin

# Build rule for target.
client.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client.bin
.PHONY : client.bin

# fast build rule for target.
client.bin/fast:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/build
.PHONY : client.bin/fast

#=============================================================================
# Target rules for targets named server.bin

# Build rule for target.
server.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server.bin
.PHONY : server.bin

# fast build rule for target.
server.bin/fast:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/build
.PHONY : server.bin/fast

src/client/client.o: src/client/client.cpp.o

.PHONY : src/client/client.o

# target to build an object file
src/client/client.cpp.o:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/client/client.cpp.o
.PHONY : src/client/client.cpp.o

src/client/client.i: src/client/client.cpp.i

.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.cpp.i:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/client/client.cpp.i
.PHONY : src/client/client.cpp.i

src/client/client.s: src/client/client.cpp.s

.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.cpp.s:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/client/client.cpp.s
.PHONY : src/client/client.cpp.s

src/common/User.o: src/common/User.cpp.o

.PHONY : src/common/User.o

# target to build an object file
src/common/User.cpp.o:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/User.cpp.o
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/User.cpp.o
.PHONY : src/common/User.cpp.o

src/common/User.i: src/common/User.cpp.i

.PHONY : src/common/User.i

# target to preprocess a source file
src/common/User.cpp.i:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/User.cpp.i
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/User.cpp.i
.PHONY : src/common/User.cpp.i

src/common/User.s: src/common/User.cpp.s

.PHONY : src/common/User.s

# target to generate assembly for a file
src/common/User.cpp.s:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/User.cpp.s
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/User.cpp.s
.PHONY : src/common/User.cpp.s

src/common/cause.o: src/common/cause.cpp.o

.PHONY : src/common/cause.o

# target to build an object file
src/common/cause.cpp.o:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/cause.cpp.o
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/cause.cpp.o
.PHONY : src/common/cause.cpp.o

src/common/cause.i: src/common/cause.cpp.i

.PHONY : src/common/cause.i

# target to preprocess a source file
src/common/cause.cpp.i:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/cause.cpp.i
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/cause.cpp.i
.PHONY : src/common/cause.cpp.i

src/common/cause.s: src/common/cause.cpp.s

.PHONY : src/common/cause.s

# target to generate assembly for a file
src/common/cause.cpp.s:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/cause.cpp.s
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/cause.cpp.s
.PHONY : src/common/cause.cpp.s

src/common/socket.o: src/common/socket.cpp.o

.PHONY : src/common/socket.o

# target to build an object file
src/common/socket.cpp.o:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/socket.cpp.o
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/socket.cpp.o
.PHONY : src/common/socket.cpp.o

src/common/socket.i: src/common/socket.cpp.i

.PHONY : src/common/socket.i

# target to preprocess a source file
src/common/socket.cpp.i:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/socket.cpp.i
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/socket.cpp.i
.PHONY : src/common/socket.cpp.i

src/common/socket.s: src/common/socket.cpp.s

.PHONY : src/common/socket.s

# target to generate assembly for a file
src/common/socket.cpp.s:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/socket.cpp.s
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/socket.cpp.s
.PHONY : src/common/socket.cpp.s

src/common/util.o: src/common/util.cpp.o

.PHONY : src/common/util.o

# target to build an object file
src/common/util.cpp.o:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/util.cpp.o
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/util.cpp.o
.PHONY : src/common/util.cpp.o

src/common/util.i: src/common/util.cpp.i

.PHONY : src/common/util.i

# target to preprocess a source file
src/common/util.cpp.i:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/util.cpp.i
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/util.cpp.i
.PHONY : src/common/util.cpp.i

src/common/util.s: src/common/util.cpp.s

.PHONY : src/common/util.s

# target to generate assembly for a file
src/common/util.cpp.s:
	$(MAKE) -f CMakeFiles/client.bin.dir/build.make CMakeFiles/client.bin.dir/src/common/util.cpp.s
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/common/util.cpp.s
.PHONY : src/common/util.cpp.s

src/server/Pool.o: src/server/Pool.cpp.o

.PHONY : src/server/Pool.o

# target to build an object file
src/server/Pool.cpp.o:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/server/Pool.cpp.o
.PHONY : src/server/Pool.cpp.o

src/server/Pool.i: src/server/Pool.cpp.i

.PHONY : src/server/Pool.i

# target to preprocess a source file
src/server/Pool.cpp.i:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/server/Pool.cpp.i
.PHONY : src/server/Pool.cpp.i

src/server/Pool.s: src/server/Pool.cpp.s

.PHONY : src/server/Pool.s

# target to generate assembly for a file
src/server/Pool.cpp.s:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/server/Pool.cpp.s
.PHONY : src/server/Pool.cpp.s

src/server/Pools.o: src/server/Pools.cpp.o

.PHONY : src/server/Pools.o

# target to build an object file
src/server/Pools.cpp.o:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/server/Pools.cpp.o
.PHONY : src/server/Pools.cpp.o

src/server/Pools.i: src/server/Pools.cpp.i

.PHONY : src/server/Pools.i

# target to preprocess a source file
src/server/Pools.cpp.i:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/server/Pools.cpp.i
.PHONY : src/server/Pools.cpp.i

src/server/Pools.s: src/server/Pools.cpp.s

.PHONY : src/server/Pools.s

# target to generate assembly for a file
src/server/Pools.cpp.s:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/server/Pools.cpp.s
.PHONY : src/server/Pools.cpp.s

src/server/server.o: src/server/server.cpp.o

.PHONY : src/server/server.o

# target to build an object file
src/server/server.cpp.o:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/server/server.cpp.o
.PHONY : src/server/server.cpp.o

src/server/server.i: src/server/server.cpp.i

.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.cpp.i:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/server/server.cpp.i
.PHONY : src/server/server.cpp.i

src/server/server.s: src/server/server.cpp.s

.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.cpp.s:
	$(MAKE) -f CMakeFiles/server.bin.dir/build.make CMakeFiles/server.bin.dir/src/server/server.cpp.s
.PHONY : src/server/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... client.bin"
	@echo "... edit_cache"
	@echo "... server.bin"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/common/User.o"
	@echo "... src/common/User.i"
	@echo "... src/common/User.s"
	@echo "... src/common/cause.o"
	@echo "... src/common/cause.i"
	@echo "... src/common/cause.s"
	@echo "... src/common/socket.o"
	@echo "... src/common/socket.i"
	@echo "... src/common/socket.s"
	@echo "... src/common/util.o"
	@echo "... src/common/util.i"
	@echo "... src/common/util.s"
	@echo "... src/server/Pool.o"
	@echo "... src/server/Pool.i"
	@echo "... src/server/Pool.s"
	@echo "... src/server/Pools.o"
	@echo "... src/server/Pools.i"
	@echo "... src/server/Pools.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

