#ifndef IUT_CLIENTSERVEUR_MINIPROJET_PROTOCOL_H
#define IUT_CLIENTSERVEUR_MINIPROJET_PROTOCOL_H

#define PROTOCOL_NO_METHOD -1
#define PROTOCOL_METHOD_NEW_GAME 0
#define PROTOCOL_METHOD_JOIN_POOL 1
#define PROTOCOL_METHOD_WANTS_TO_PLAY 2

#endif //IUT_CLIENTSERVEUR_MINIPROJET_PROTOCOL_H
