//
// Created by kocal on 03/04/16.
//

#ifndef IUT_CLIENTSERVEUR_MINIPROJET_PROTOCOL_H
#define IUT_CLIENTSERVEUR_MINIPROJET_PROTOCOL_H

#define PROTOCOL_NO_METHOD -1
#define PROTOCOL_METHOD_NEW_GAME 0
#define PROTOCOL_METHOD_JOIN_POOL 1

#endif //IUT_CLIENTSERVEUR_MINIPROJET_PROTOCOL_H
