//
// Created by kocal on 03/04/16.
//

#ifndef IUT_CLIENTSERVEUR_MINIPROJET_PROTOCOL_H
#define IUT_CLIENTSERVEUR_MINIPROJET_PROTOCOL_H

#define PROTOCOL_NEW_GAME "NEW_GAME"
#define PROTOCOL_JOIN_POOL "JOIN_POOL"

#endif //IUT_CLIENTSERVEUR_MINIPROJET_PROTOCOL_H
